# АНАЛИЗ ДАННЫХ И МАШИННОЕ ОБУЧЕНИЕ

Данные наделяют нас знаниями. Независимо от того, проводите ли вы опрос для измерения удовлетворенности клиентов или проводите химический эксперимент, вы хотите что-то получить из собранных данных.

Данные могут быть неправильно поняты или неверно истолкованы. Тем не менее анализ данных позволяет сгенерировать надежные знания. У разных ученых разные подходы к анализу данных, зачастую это зависит от характера исследований и объема имеющихся данных. В течение следующих занятий мы научимся собирать, обрабатывать, исследовать и обобщать данные, а также строить различные модели для решения разнообразных задач.

Вся работа будет происходить в интерактивных ноутбуках (.ipynb), которые вы можете запускать как в [Юпитере](https://practicum.yandex.ru/blog/chto-takoe-jupyter-notebook/), так и в облачной платформе [Google Colaboratory](https://colab.research.google.com/notebooks/intro.ipynb?hl=ru%20here)

Python — это один из самых распространённых языков программирования. Хотя стандартные возможности Python достаточно скромны, существует огромное количество пакетов, которые позволяют решать с помощью этого языка самые разные задачи. Пожалуй, именно поэтому Python и пользуется такой популярностью среди программистов. 

Для решения задач анализа данных и машинного обучения мы будем (в основном) пользоваться следующими библиотеками:
   1. `NumPy` — это один из самых широко используемых Python-пакетов. Название пакета, NumPy, расшифровывается как Numerical Python. Здесь реализовано множество вычислительных механизмов, пакет поддерживает специализированные структуры данных, в том числе — одномерные и многомерные массивы, значительно расширяющие возможности Python по выполнению различных вычислений.
   2. Пакет `SciPy` построен на основе NumPy, в нём используются и некоторые другие вспомогательные пакеты. Он широко используется для выполнения статистических расчётов. 
   3. `Pandas` — это, после NumPy, второй по известности Python-пакет, используемый в Data Science. Его применяют в самых разных местах, например, в сферах статистики, финансов, экономики, анализа данных. Пакет Pandas часто используют для обработки больших объёмов данных. Фактически, для проведения DS-вычислений обычно используются все три пакета — Pandas, NumPy и SciPy.
   4. `Matplotlib` — это известнейший Python-пакет для визуализации данных. Его, пожалуй, можно включить в набор основных пакетов, которые нужно освоить тому, кто пользуется Python в сфере Data Science. Он поддерживает множество стандартных средств для визуализации данных, представленных различными графиками и диаграммами.
   5. `Scikit-Learn` — это Python-пакет для машинного обучения. Он включает в себя практически всё, что нужно дата-cатанисту (это не ошибка :)).

# `Pandas`

Библиотека Pandas - важная библиотека, с которой мы начнем знакомство и будем активно работать в этом учебном модуле. Pandas $-$ это модуль для первичной работы с данными, с помощью которого можно проводить простой анализ данных и предобработку данных.
Основные возможности:
* удобное чтение и запись данных из csv, txt, xls, SQL databases, HDF5
* удобная работа с пропусками в данных
* поиск, сортировка, выборка объектов, удовлетворяющих заданным критериям
* возможности по соединению датасетов
* красивая визуализация

Импорт библиотеки:

In [ ]:
# Данная конструкция подключает модуль pandas и позволяет обращаться 
# к его функциям через имя pd (при желании вы можете использовать и другое короткое имя, но pd - общеупотребимое).
import pandas as pd

In [ ]:
import numpy as np

## 1. Создание объекта

Основу <b>Pandas</b> составляют такие структуры данных, как <b>Series и DataFrame</b>.

Подробнее см. [Введение в структуры данных pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html#dsintro)

<b>Series</b> - это <b>одномерный массив</b>, имеющий специальные <b>метки (индексы)</b> и способные хранить данные <b>любого</b> типа.

![pandas-series-cummin-image-1.svg]()

In [ ]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

В строковом представлении Series, отображаемом в интерактивном режиме, индекс находится слева, а значения справа. Поскольку мы не задали индекс для данных, то по умолчанию индекс задается как `range(n)`. 

Получить информацию о содержании и индексировании массива можно с помощью аттрибутов `values` и `index` соответственно:

In [ ]:
print(s.values)
print(s.index)

Чтобы создать объект Series с индексом, индентифицирующим каждый элемент данных в соответсвии с некоторым смыслом, можно использовать в индексе  метки:

In [ ]:
obj1=pd.Series([25,15,20,20], index=['left','right', 'top','bottom'])
obj1

<b>DataFrame</b> - это <b>двумерный массив (матрица, таблица)</b>, имеющий <b>специальные метки (индексы)</b>, который хранит в своих столбцах данные <b>разных типов</b>.

![dataframe.png]()

### Создание DataFrame внутренними средствами Python
Создаем DataFrame из словаря:

In [ ]:
my_dict={'state':['Ohio','Ohio','Ohio','Nevada', 'Nevada','Nevada'], 
          'year':[2000, 2001, 2002, 2001, 2002, 2003],
          'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]} # словарь, все значения которого - списки
df=pd.DataFrame(my_dict) # создание объекта DataFrame из словаря. Ключи становятся столбцами
df

Создадим датафрейм с временными метками в качестве индекса и заполним его случайными значениями

In [ ]:
# указываем начало временнОго периода и число повторений (дни по умолчанию)
dates = pd.date_range('20130101', periods=6) 
dates

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df

Или так

In [ ]:
df2 = pd.DataFrame({'A': 1.,
                    'B': pd.Timestamp('20130102'), # временнАя метка
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'), # Серия на основе списка
                    'D': np.array([3] * 4, dtype='int32'), # массив целых чисел NumPy 
                    'E': pd.Categorical(["test", "train", "test", "train"]), # категории
                    'F': 'foo'})
df2

Столбцы итогового [`DataFrame`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html#pandas.DataFrame) имеют разные [типы данных](https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#basics-dtypes), в зависимости от того, что за данные хранятся в столбце.

In [ ]:
df2.dtypes

Если вы используете `IPython` или `Jupyter (Lab) Notebook (Colab)`, то по нажатию TAB после точки отобразятся публичные атрибуты объекта (в данном случае `DataFrame`):

In [ ]:
# Попробуйте убрать комментарий и нажать TAB
df2.

## 2. Загрузка данных

Зачастую данные уже хранятся в каком-нибудь файле и нам нужно только их считать для работы.

__Наиболее популярные форматы данных (при скачивании датасета из интернета)__:
* _csv_ (comma separated file), _tsv_ (tab separated file) - таблицы, записанные в текстовые файлы с простой структурой. Эти файлы можно открывать в обычном текстовом редакторе. Pandas позволяет считывать эти данные именно в формате таблицы.
* _xls_ (eXceL Spreadsheet $-$ таблицы Microsoft)
* _json_ (JavaScript Object Notation, используется для _сериализации_ структур языка, то есть сохранения сложных объектов, например, вложенных списков или словарей python). Json-текст представляет собой либо набор пар ключ: значение, либо упорядоченный набор значений
* _txt_ в иной специфичной для задачи форме (например, vowpal-wabbit и uci bag-of-words для <<мешка слов>>)

В pandas есть функции для считывания во всех этих форматах.

В реальной жизни данные хранятся в базах данных, откуда с помощью sql-подобных языков из них составляют файлы в указанных выше форматах.

__Чтение из csv с помощью pandas__:
[pandas.read_csv()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html)
У функции несколько параметров, основные необходимые:
* filepath_or_buffer (перый и единственный обязательный аргумент) --- имя файла
* sep $-$ разделитель (; , \t ...)
* quotechar $-$ символ кавычек, все что внутри считается за строку (разделители также могут входить в эту строку; ' " ...)
* names $-$ список названий колонок
* header $-$ номер строки файла (с 0), которую нужно считать заголовком
* dtype $-$ словарь, сопоставляющий именам колонок типы данных в них
* na_values $-$ строка/список/словарь (ключи $-$ названия колонок) строковых значений, которые нужно считать пропуском.

По умолчанию names=None и header=0, то есть названия колонок берутся из первой строки файла. Можно передать названия через names. Если вы не хотите давать названия, укажите header=None, тогда названия будут даны автоматически индексами с 0. Учтите, что названия нужны при дальнейшей работе с данными (если вы только не собираетесь взять оттуда только numpy-матрицу; в этом случае они не понадобятся). Следите за длиной списка названий, он должен совпадать с реальным числом колонок в файле! Чтобы заменить заголовки, записанные в файле, нужно установить header=0 и передать names.

В функцию pd.read\_csv можно передавать как путь к файлу, хранящемуся на компьютере, так и ссылку на файл в Интернете.

Для чтения xls: [pandas.read_excel](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_excel.html)

Для чтения sql: [pandas.read_sql](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql.html)

Считывание данных:

In [ ]:
df = pd.read_csv("titanic.csv", sep=";")

Мы будем работать с данными [Titanic](https://www.kaggle.com/c/titanic): он содержит информацию о пассажирах корабля, включая их демографические характеристики и выжил пассажир или нет.

In [ ]:
df

Каждая строчка набора данных содержит следующие поля:

- `PassengerId` — номер пассажира;

- `Survived` — выжил данный пассажир или нет (0 для умерших, 1 для выживших);

- `Pclass` — класс пассажира (1 — высший, 2 — средний, 3 — низший);

- `Name` — имя;

- `Sex` — пол;

- `Age` — возраст;

- `SibSp` — количество братьев, сестер, сводных братьев, сводных сестер, супругов на борту титаника;

- `Parch` — количество родителей, детей (в том числе приемных) на борту титаника;

- `Ticket` — номер билета;

- `Fare` — плата за проезд;

- `Cabin` — каюта;

- `Embarked` — порт посадки (C — Шербур; Q — Квинстаун; S — Саутгемптон).

## 3. Просмотр данных

Подробнее см. [Документацию по базовой функциональности](https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#basics).

Просмотрим верхние и нижние строки полученного кадра данных:

In [ ]:
df.head()

In [ ]:
df.tail(3) # вывести последние три строки

Посмотреть размер таблички (число наблюдений X число признаков)

In [ ]:
df.shape

In [ ]:
type(df)

Краткое описание таблицы можно вывести так:

In [ ]:
df.info()

Сортировка по столбцам, см. [`sort_index()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_index.html):

In [ ]:
df.sort_index(axis=1, ascending=False) # по умолчанию axis=0, т.е. сортировка по строкам

Сортировка по значениям, см. [`sort_values()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values):

In [ ]:
df.sort_values(by='Survived') # по умолчанию сортировка по индексу, выбрали столбец 'Survived'

## 4. Работа со строками и столбцами датафрейма

Датафрейм - это таблица. Названия строк:

In [ ]:
# Важно, потому что иногда полезно в качестве названий строк выбрать какой-то столбец таблицы
df.index

Названия столбцов:

In [ ]:
df.columns

Выбор столбца, который возвращает [`Series`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html#pandas.Series), эквивалентно `df.A`:

In [ ]:
df['Sex']

In [ ]:
df.Sex

Чтобы извлечь несколько столбцов, нужно в квадратных скобках `[]` передать **список** названий столбцов:

In [ ]:
df[["Age", "Sex", "Cabin"]]

In [ ]:
print(df.columns[0])
print(df.dtypes)

В машинном обучении библиотеку удобно использовать со следующей интерпретацией: по строкам датафрейма находятся объекты, по столбцам - признаки и целевая переменная. В нашем датафрейме целевая переменная задана в столбце `Survived`. Если мы бы хотели выделить часть датафрейма без этого столбца, мы бы использовали такой код:

In [ ]:
# axis указываем, потому что так требует pandas
df.drop("Survived", axis = 1).head()

Обратите внимание, что столбец не удалился из датафрейма навсегда. Наоборот, результат нашей операции записан в выводе, и если бы мы хотели его сохранить, мы должны были бы присвоить результат операции новой переменной.

Доступ к **строкам** по индексу, т. е. выбор с помощью `[ ]` вырезает строки:

In [ ]:
df[0:3]

**Обратиться к отдельному элементу или сделать срез данных** можно с помощью методов `loc` и `iloc`. Они позволяют выбрать подмножество строк и столбцов, используя либо метки строк (`loc`), либо целые числа (`iloc`).
[Подробнее о различиях между loc и iloc](https://towardsdatascience.com/how-to-use-loc-and-iloc-for-selecting-data-in-pandas-bd09cb4c3d79#:~:text=The%20main%20distinction%20between%20loc,0%2Dbased%20integer%20position)

### Выбор по метке

In [ ]:
# Если передавать индексы как названия
df.loc[:3, 'Name']  # метка строки, метки столбцов

Выбор по нескольким осям:

In [ ]:
df.loc[:, ['Name', 'Ticket']]

### Выбор по позиции

Выбор позиции с помощью целых чисел:

In [ ]:
df.iloc[3]

По целочисленным срезам, действующим аналогично NumPy / Python, т.е. правое граничное значение не включается:

In [ ]:
df.iloc[3:5, 0:2]  # номера строк, номер столбца

По спискам целочисленных позиций, аналогично стилю NumPy / Python:

In [ ]:
df.iloc[[1, 2, 4], [0, 2]]

Для явного создания среза строк:

In [ ]:
df.iloc[1:3, :]

Для явного создания среза столбцов:

In [ ]:
df.iloc[:, 1:3]

Для явного получения значений:

In [ ]:
df.iloc[2, 4]

### Булево индексирование

Иногда бывает нужно вывести строки с фиксированными значениями нескольких полей.

Использование значений одного столбца для выбора данных:

In [ ]:
df[df['Age'] > 0]

In [ ]:
df[(df['Age'] > 0) & (df['Sex'] == 'female')]

#### Копирование объектов Pandas

1. В Python операция присваивания создает **ссылку** на объект, стоящий справа, поэтому если после выполнения такого кода:

        df1=pd.Dataframe(my_dict)
        df2=df1
    
    вы решите изменить `df2`, например, то те же самые изменения произойдут и с `df1`, потому что и та, и другая переменная ссылаются на один и тот же объект.
    
2. При выполнениее кода
        `object_new=object.copy(deep=True)` 
    (параметр `deep` равен `True` по умолчанию) происходит создание нового **объекта** и копирование в него индексов и содержания исходного объекта `object`.

In [ ]:
df2 = df.copy() # создаем копию исходгого кадра данных

Использование метода [`isin()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.isin.html#pandas.Series.isin) для фильтрации:

In [ ]:
df2[df2['Sex'].isin(['female'])] # фильтруем

## 5.  Отсутствующие данные

pandas в основном использует значение [`np.nan`](https://numpy.org/doc/stable/user/misc.html) для представления отсутствующих данных. По умолчанию они не включается в вычисления, см. подробнее в [Документации](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html#missing-data)

In [ ]:
df.info()

Чтобы удалить строки, в которых отсутствуют данные, см. [`dropna()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html):

In [ ]:
df.dropna() # how='any', axis=0 по умолчанию, т.е. удаляются все строки с пропущенными данными

Заполнение недостающих данных:

In [ ]:
df.fillna(value=5)

Чтобы получить логическую маску, в которой значениями являются nan.

In [ ]:
pd.isna(df)

## 6. Получение и запись данных

### CSV

см. [про запись в csv файлы](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-store-in-csv)

In [ ]:
df.to_csv('df.csv')

см. [про чтение csv файлов](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-read-csv-table)

In [ ]:
pd.read_csv('df.csv')

### Excel

см. [про чтение и запись в MS Excel](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-excel)

Запись в excel файл:

In [ ]:
df.to_excel('df.xlsx', sheet_name='Sheet1')

Чтение из excel файла:

In [ ]:
pd.read_excel('df.xlsx', 'Sheet1', index_col=None, na_values=['NA'])

## 7. Анализ и преобразование датафрейма

In [ ]:
df = pd.read_csv("titanic.csv", sep=";")

Основная информация по датафрейму:

In [ ]:
df.describe()

По этим статистикам можно понять, одинаковый ли масштаб имеют признаки (например, Age измеряется от 0 до 80, а Pclass в единицах - от 1 до 3). Также можно понять, есть ли пропуски в данных (по count). Например, в графе Age есть пропуски.

Использовать столбец Name для задания названий строк (index):

In [ ]:
df.set_index(df["Name"], inplace=True)

In [ ]:
df.head()

Теперь строки индексируются с помощью Name (выделено жирным в начале каждой строки).

Уникальные значения в столбце:

In [ ]:
set(df["Sex"])

In [ ]:
df['Sex'].unique()

Уникальные значения в столбце с числом строк с таким значением:

In [ ]:
df["Sex"].value_counts()

Перекодирование столбца с помощью функции map:

In [ ]:
sex = df["Sex"]
sex.map({"male":1, "female":-1, "unknown":0}).head()

Функция apply: применение функции поэлементно к столбцу или строке (+ создание нового столбца, потому что apply возвращает результат и никак не модифицирует датафрейм)

In [ ]:
def func(x):
    return x + 100

In [ ]:
df["NewAge"] = df["Age"].apply(lambda x: x+100)

In [ ]:
df.head()

Полезные методы (команды для массивов):
- `.sum()` – сумма элементов;
- `.count()` – количество появлений элемента;
- `.mean()` – среднее элементов;
- `.min()` – минимальный элемент;
- `.max()` – максимальный элемент.

In [ ]:
df['Age'].mean()

Функция groupby: создание групп по значению какого-то столбца (или группы столбцов)

In [ ]:
df.groupby("Sex")['Age'].apply(lambda x: x.mean())

Создаем столбец с фамилией:

In [ ]:
df["Family"] = df["Name"].apply(lambda s: s.split(";")[0])

In [ ]:
df.head()

In [ ]:
df.groupby("Family")["Age"].count().head()

Сколько семей, в которых больше трех человек?

In [ ]:
(df.groupby("Family")["Age"].count() > 3).sum()

# Немного заданий, которые позволят нам "понять" данные

### Задача 1. Какова доля семей, в которых минимальный возраст меньше 20 (семьи с детьми)?

### Задача 2. Какова доля выживших пассажиров из класса 3? А пассажиров из класса 1?

### Задача 3. Сколько пассажиров выжило, а сколько - нет?

### Задача 4. Создайте столбец "IsChild", который равен 1, если возраст меньше 20, и 0 иначе. Для пропущенных значений поведение функции может быть произвольным.

### Задача 5. Какова доля выживших женщин из первого класса? А доля выживших мужчин из 3 класса?

**Вывод: <font color='white'>  если вы небогатый мужчина, то трансатлантические переезды по воде в начале XX века вам лучше не совершать.**</font>